blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/tuxtechlab/test-gpp-sign/discussions
    about: Need help selfhosting or ask a general question about the project? Open a discussion.
  - name: Discord
    url: https://discord.gg/wTPB9XQ4V
    about: Join our Discord community for real-time discussions and support.
  - name: LinkedIn
    url: https://linkedin.com/company/tuxtechlab
    about: Follow us on LinkedIn for updates and news.